### ISSUE TITLE
Facebook loginpage clone

### ISSUE THREAD

**Issue by NishikantaRay** [NishikantaRay/Login-Signup-Templates#50]

**Comment by NishikantaRay** [comment]
With validation

**Comment by durgeshahire07** [comment]
what do we need to validate? pls specify more

**Comment by JanviRaina** [comment]
Hey! I can try making Facebook login page clone. You can assign this to me

**Comment by yogesh2k21** [comment]
Please assign it to me 
i have a cool fb login clone
