### ISSUE TITLE
App for displaying all the signup and signin page

### ISSUE THREAD

**Issue by NishikantaRay** [NishikantaRay/Login-Signup-Templates#94]

**Comment by NishikantaRay** [comment]
Using Neumorphism ui.

**Comment by NishikantaRay** [comment]
How you will do it ? means automation 
If you're interested then. I will assign you

**Comment by Shivansh-yadav13** [comment]
> How you will do it ? means automation If you're interested then. I will assign you

I can add them manually :)

**Comment by NishikantaRay** [comment]
it's okk do it using Neumorphism UI and data should call from a json data

**Comment by NishikantaRay** [comment]
Any progress?

**Comment by Jobin-S** [comment]
can I do this feature @NishikantaRay

**Comment by NishikantaRay** [comment]
Yes
